## Training parameters
state: CA
model: rf
lr:
  random_state: 1
  solver: 'lbfgs'
rf:
  random_state: 1
  n_estimators: 100
  max_depth: 10
  max_leaf_nodes: 100
sample:
  random_state: 1
  test_size: 0.2
evaluation:
  - f1
  - auc
categorical_cols:
  - job
  - category
  - merchant
models_dir: src/artifacts/
raw_data_dir: src/data/raw/
processed_data_dir: src/data/processed/